name: General CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trigger_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Checkout Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: checkout.yml
          ref: ${{ github.ref }}

  trigger_maven_build:
    runs-on: ubuntu-latest
    needs: trigger_checkout  # Este trabajo depende de 'trigger_checkout'
    steps:
      - name: Trigger Maven Build Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: maven-build.yml
          ref: ${{ github.ref }}

  trigger_docker_build:
    runs-on: ubuntu-latest
    needs: trigger_maven_build  # Depende de 'trigger_maven_build'
    steps:
      - name: Trigger Docker Build Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: docker-build.yml
          ref: ${{ github.ref }}

  trigger_docker_push:
    runs-on: ubuntu-latest
    needs: trigger_docker_build  # Depende de 'trigger_docker_build'
    steps:
      - name: Trigger Docker Push Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: docker-push.yml
          ref: ${{ github.ref }}

  trigger_render_deploy:
    runs-on: ubuntu-latest
    needs: trigger_docker_push  # Depende de 'trigger_docker_push'
    steps:
      - name: Trigger Deploy to Render
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: render-deploy.yml
          ref: ${{ github.ref }}
