name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          # Paso 1: Chequear el código del repositorio
          - name: Checkout code
            uses: actions/checkout@v4
    
          # Paso 2: Configurar Docker Buildx (para crear la imagen)
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
    
          # Paso 3: Configurar Maven y construir el proyecto
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
            
          - name: Build with Maven
            run: mvn clean package -DskipTests   
            
           # Paso 4: Construir la imagen Docker
          - name: Build the Docker image
            run: docker build --platform linux/amd64 -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_APP_NAME}}:${{secrets.DOCKER_APP_TAG}} .

           # Paso 5: Iniciar sesión en Docker Hub
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

           # Paso 6: Hacer push de la imagen a Docker Hub
          - name: Push Docker image
            run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_APP_NAME}}:${{secrets.DOCKER_APP_TAG}}
