name: Build with Maven

on:
  workflow_dispatch:  # Este workflow será disparado por el workflow general

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests -P docker -f pom.xml
