name: Publish Package

on:  
  workflow_dispatch:

jobs:
  publish-api-smartpot-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: SmartPot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish the API Docker image
        run: |
          docker build . --tag ghcr.io/smartpot/api-smartpot:latest
          docker run ghcr.io/smartpot/api-smartpot:latest
          docker push ghcr.io/smartpot/api-smartpot:latest
