name: Publish Package

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish-api-smartpot-image:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configuración de JDK 17 para la construcción del proyecto Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3: Construcción del proyecto usando Maven (sin pruebas y perfil docker)
      - name: Build with Maven
        run: mvn clean package -DskipTests -P docker -f pom.xml

      # Paso 4: Login al GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: smartpot
          password: ${{ secrets.GHCR_PAT }}

      # Paso 5: Construcción de la imagen Docker
      - name: Build the API Docker image
        run: docker build --platform linux/amd64 -t ghcr.io/smartpot/api-smartpot:latest .

      # Paso 6: Push de la imagen Docker al GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/smartpot/api-smartpot:latest
